# Generated by Django 5.0 on 2023-12-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_record_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
