# Generated by Django 5.0 on 2023-12-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_records_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='emamil',
            new_name='email',
        ),
    ]
